### ISSUE TITLE
no sensors output

### ISSUE THREAD

**Issue by mrmodolo** [kz6fittycent/bashtop#2]
Hi!

I have the sensors command installed and configured, I edited the file /snap/bashtop/current/.config/bashtop/bashtop.cfg putting the option check_temp = "true". But whenever the bashtop command is executed, the value returns to false and no temperature information is displayed!

```
$ sensors
dell_smm-virtual-0
Adapter: Virtual device
Processor Fan: 2800 RPM
fan2:          2800 RPM
fan3:          2800 RPM
CPU:            +48.0°C  
Other:          +45.0°C  
SODIMM:         +39.0°C  
GPU:            +43.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.84 V  
curr1:       1000.00 uA 

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +49.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +49.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +47.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +25.0°C  (crit = +107.0°C)
```
Thanks,

Marcelo Módolo

**Comment by Benedolt** [comment]
Same here! Switching on temp support in the menu also doesn't work. It's just stuck on "false".

**Comment by toikpi** [comment]
I encountered the same problem on Ubuntu 20.04 x86 64 bit. I wonder if the problem is a seccomp violation.

CPU Temperature monitoring not available in the snap but works when bashtop is installed from source.

I installed the snap and ran bashtop. I used the Options sub-menu and found that it was not possible to "check temp" option to true.

I resinstalled the snap in developer mode and examined the system log as described on the Snapcraft site (https://snapcraft.io/docs/debug-snaps). I excluded the ALLOWED and STATUS entries and was left with a single entry with a SECCOMP violation when the script tries to call sed.

Here is a tidied version of my checks.

```
$ cat !$
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
$ 
$ uname -a
Linux hostname 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ 
$ sudo journalctl --since "2020-08-27 07:30:00" | grep audit | grep bashtop | grep -v -e ALLOWED -e STATUS
Aug 27 07:40:39 hostname audit[7926]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=7926 comm="sed" exe="/snap/bashtop/122/bin/sed" sig=0 arch=c000003e syscall=93 compat=0 ip=0x7efc5bcbb527 code=0x7ffc0000
$ 
$ sudo journalctl --since "2020-08-27 07:30:00" | grep audit | grep bashtop | grep -i sensor
$
```

I wonder if the SECCOMP log message indicates a wider problem which means that the sensors binary contained in the snap is not visible to the bashtop script. See - https://snapcraft.io/docs/debug-snaps#heading--seccomp.

I then removed the snap and installed bashtop from source and found that CPU temperature monitoring works.

Thanks in advance.

**Comment by toikpi** [comment]
I noticed the `snap connect ...` commands on Snapcraft (https://snapcraft.io/install/bashtop/ubuntu). I removed the install of bashtop from source, reinstalled the snap and ran the listed `snap connect` commands. I then ran bashtop, it locked up on the "splash" page when checking memory.

I have reverted to the install from source.

Sorry to provide more bad news.

**Comment by Benedolt** [comment]
Just FYI: I've switched to using the bpytop snap where temps display works. (Bpytop is a python reimplementation of bashtop by the original developer. They recommend using that as they aren't actively developing bashtop any more.)

**Comment by toikpi** [comment]
@Benedolt thanks for the update.
I have installed your snap of bpytop as you suggested. It worked straight away.
Thank you for your effort (and snaps).

**Comment by Benedolt** [comment]
@toikpi Glad it works for you! It's not my snap, though. That's all @kz6fittycent  :)

**Comment by kz6fittycent** [comment]
That particular switch (temp) seems to glitch when first turning "on" and I don't know why. I noticed the same thing when running the `.deb` on an Ubuntu server I have at work. I typically have to switch the "tree" setting a couple of times, too. Given that I'm seeing the same issue between the `.deb` version and the snap, I've just chalked it up to the software itself. 

That said, did you ensure that you have all the snap connections? If you don't, then that switch will never work -ever. 

```
sudo snap connect bashtop:mount-observe

sudo snap connect bashtop:network-control

sudo snap connect bashtop:hardware-observe

sudo snap connect bashtop:system-observe

sudo snap connect bashtop:process-control

```
